export * from './protocol';
export {
  initBleManager as initPeripheralBle,
  startAdvertising,
  stopAdvertising,
  handleIncomingTransaction,
  getCurrentPaymentRequest,
  getPeripheralState,
  getCurrentEphemeralKey,
  destroyBleManager as destroyPeripheralBle,
  type PeripheralState,
  type ReceivedPayment,
  type PeripheralCallbacks,
} from './peripheral';
export {
  initBleManager as initCentralBle,
  startScanning,
  stopScanning,
  connectToDevice,
  readPaymentRequest,
  sendPayment,
  sendPaymentDirect,
  disconnectDevice,
  getDiscoveredDevices,
  getCentralState,
  isConnected,
  destroyBleManager as destroyCentralBle,
  type CentralState,
  type DiscoveredDevice,
  type CentralCallbacks,
} from './central';
